#!/usr/bin/env python3

import sys
from tb import Application, ConfigFromArgs, ConfigFromFile, ConfigFile, ConfigDefault

app = Application(
	ConfigFromArgs(
		sys.argv,
		ConfigFromFile(
			ConfigFile(
				ConfigFromArgs(
					sys.argv,
					ConfigDefault({'config': '/etc/telebot.conf'})
				)
			),
			ConfigDefault({})
		)
	)
)
app.run()
